apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "botforge.fullname" . }}-initdb
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
data:
  create.sql: |
{{ .Files.Get "files/create.sql" | indent 4 }}
