{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botforge.fullname" . }}-mongo
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "botforge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "botforge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}"
          ports:
            - name: mongo
              containerPort: {{ .Values.mongo.service.port }}
              protocol: TCP
          env:
            {{- range $key, $val := .Values.mongo.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
{{- end }}
