{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botforge.fullname" . }}-mongo
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "botforge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "botforge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}"
          ports:
            - name: mongo
              containerPort: {{ .Values.mongo.service.port }}
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongo.env.MONGO_INITDB_ROOT_USERNAME }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "botforge.fullname" . }}-secrets
                  key: mongo-password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
{{- end }}
