apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "botforge.fullname" . }}-postgres
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "botforge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "botforge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "botforge.fullname" . }}-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.env.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.env.POSTGRES_USER }}"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/create.sql
              subPath: create.sql
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: initdb
          configMap:
            name: {{ include "botforge.fullname" . }}-initdb
