apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botforge.fullname" . }}-backend-config
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {
      {{- if .Values.mongo.enabled }}
      "mongodbUri": "mongodb://{{ .Values.mongo.env.MONGO_INITDB_ROOT_USERNAME }}:{{ .Values.mongo.env.MONGO_INITDB_ROOT_PASSWORD }}@{{ include "botforge.fullname" . }}-mongo:{{ .Values.mongo.service.port }}/botforge?authSource=admin",
      {{- else }}
      "mongodbUri": "{{ .Values.backend.config.mongodbUri }}",
      {{- end }}
      "googleClientId": "{{ .Values.backend.config.googleClientId }}",
      "jwtSecret": "{{ .Values.backend.config.jwtSecret }}",
      "UploadsDirectory": "{{ .Values.backend.config.UploadsDirectory }}",
      "MaxFileSize": {{ .Values.backend.config.MaxFileSize }},
      "firebase": {
        "apiKey": "{{ .Values.backend.config.firebase.apiKey }}",
        "authDomain": "{{ .Values.backend.config.firebase.authDomain }}",
        "projectId": "{{ .Values.backend.config.firebase.projectId }}"
      },
      "database": {
        "host": "{{ include "botforge.fullname" . }}-postgres",
        "port": "{{ .Values.backend.config.database.port }}",
        "user": "{{ .Values.backend.config.database.user }}",
        "password": "{{ .Values.backend.config.database.password }}",
        "name": "{{ .Values.backend.config.database.name }}"
      },
      "redis": {
        "address": "{{ include "botforge.fullname" . }}-redis:{{ .Values.redis.service.port }}",
        "user": "{{ .Values.backend.config.redis.user }}",
        "password": "{{ .Values.backend.config.redis.password }}",
        "db": "{{ .Values.backend.config.redis.db }}"
      },
      "publicKeyPath": "{{ .Values.backend.config.publicKeyPath }}",
      "privateKeyPath": "{{ .Values.backend.config.privateKeyPath }}",
      "ragBackendURL": "http://{{ include "botforge.fullname" . }}-rag:{{ .Values.rag.service.port }}",
      "websiteFilename": "{{ .Values.backend.config.websiteFilename }}",
      "upstashURL": "{{ .Values.backend.config.upstashURL }}",
      "upstashToken": "{{ .Values.backend.config.upstashToken }}"
    }
